# -*- coding: utf-8 -*-
"""GA_First_Map.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uiR5JJFJjjRZztwtMEnuQLTL7EF8in6C
"""

import geopandas as gpd

full_data = gpd.read_file("zip://DEC_lands.shp.zip")
full_data.head()

type(full_data)

data = full_data.loc[:, ['CLASS', 'COUNTY', 'geometry']].copy()

# How many lands of each type are there
data.CLASS.value_counts()

# Select the land that fall under the "WILD FOREST" or "WILDERNESS" category
wild_lands = data.loc[data.CLASS.isin(["WILD FOREST", "WILDERNESS"])].copy()

wild_lands.head()

#xyz = data.CLASS.isin(["WILD FOREST", "WILDERNESS"]).copy()
xyz = data[["CLASS"]].isin(["WILD FOREST", "WILDERNESS"])
xyz.head()

# Visualize on map
wild_lands.plot()

# View the first five entries in the 'geometry' column
wild_lands[["geometry"]].head()

# Campsite in New York state (points)
POI_data = gpd.read_file("Decptsofinterest.dbf.zip")

#POI_data.head()
campsites = POI_data.loc[POI_data.ASSET=='PRIMITIVE CAMPSITE'].copy()

# Foot trails in New York state (LineString)
roads_trails = gpd.read_file("Decroadstrails.dbf.zip")
#roads_trails.head()
trails = roads_trails.loc[roads_trails.ASSET=='FOOT TRAILS'].copy()

# County boundries in New York states (Polygon)
counties = gpd.read_file("NY_county_boundaries.dbf.zip")
#counties.head()

"""**Visualize on map**"""

# Define a base map with county boundaries
ax = counties.plot(figsize=(10, 10), color='none', edgecolor='gainsboro', zorder=3)

# Add 'wild_lands', 'campsites' and 'foot trails' to the base map
wild_lands.plot(color='lightgreen', ax=ax)
campsites.plot(color='maroon', markersize=2, ax=ax)
trails.plot(color='black', markersize=1, ax=ax)

